services:
  youtubeapi:
    image: ghcr.io/harryneufeld/youtubedataapiweb:latest
    container_name: youtubeapiweb
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - YOUTUBE_API_KEY=YOURAPIKEYGOESHERE
    volumes:
     - /var/youtubeapi/data:/app/Data
    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.youtubeapi.rule=Host(`example.com`)"
      #- "traefik.http.routers.youtubeapi.entrypoints=websecure"
      #- "traefik.http.routers.youtubeapi.tls.certresolver=myresolver"
      #- "traefik.http.services.youtubeapi.loadbalancer.server.port=8080"
    networks:
      - web

networks:
  web:
    external: true